name: prolif-paper
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - notebook
  - pip
  - python==3.8.5
  - rdkit==2020.03.5
  - cython
  - seaborn
  - scikit-learn==0.24.2
  - pip:
    - networkx==2.5
    - pyvis==0.1.8.2